spring:
  datasource:
    url: jdbc:sqlserver://localhost:${MSSQL_PORT:14330};databaseName=${DB_NAME:hopeful_return};encrypt=true;trustServerCertificate=true
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:16379}

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security: info
